# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-vpn-connection
  description: Terraform module to provision a site-to-site VPN connection between a VPC and an on-premises network
  homepage: https://cloudposse.com/accelerate
  topics: ""
